# Generated by Django 2.2.7 on 2019-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191123_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='githubuser',
            unique_together={('github_id',)},
        ),
    ]
